### ISSUE TITLE
Currently grabbing incorrect common name

### ISSUE THREAD

**Issue by albenson-usgs** [usgs-bcb/tir#11]
https://gc2.datadistillery.org/api/v1/sql/bcb?q=SELECT%20*%20FROM%20sgcn.sgcn_search%20WHERE%20scientificname=%27Acipenser%20oxyrinchus%27

An issue has arisen with preferring the first ITIS common name for use in the TIR. For Acipenser oxyrinchus (https://en.wikipedia.org/wiki/Acipenser_oxyrinchus) which is the higher level for both Gulf and Atlantic Sturgeon, most states along the Atlantic seaboard use that higher level taxonomy to indicate Atlantic sturgeon on their lists. In our process for common names we are grabbing the first common name to come back from ITIS which in this case is Gulf sturgeon. What this amounts to is that we have in the SGCN app a species page with states all along the Atlantic coast that have "Gulf sturgeon" on their lists.

We need to modify the TIR python code to check if the state supplied common name is in the ITIS list and if it is, prefer that name over any others.

**Comment by aulenbac** [comment]
Attached is a screen grab that illustrates the issue.
<img width="1015" alt="gulf-versus-atlantic-sturgeon" src="https://user-images.githubusercontent.com/396602/29281268-8ccc1f1a-80db-11e7-959d-b72129087e33.png">

**Comment by skybristol** [comment]
This should get resolved when I run some updates here in just a bit. I'm currently running through the 1879 cases where ITIS names were not found with a fix to the ITIS matching code where I was incorrectly configuring the fuzzy match query. That's picking up a few more matches. I also updated the TIR Common Properties code and an associated function in bis/sgcn to get the most used common name from SGCN submissions and prefer that over an ITIS name. I will reset and rerun TIR Common Properties for all SGCN records once the ITIS fix wraps up.
